#!/bin/bash

echo "🆓 PactaImpact Free Hosting Deployment"
echo "==================================="
echo ""

echo "📋 **Available Free Hosting Options:**"
echo ""
echo "1. 🚀 **Vercel (Frontend) + Railway (Backend)** - RECOMMENDED"
echo "   ✅ Completely FREE"
echo "   ✅ Zero configuration"
echo "   ✅ Automatic deployments"
echo "   ✅ Custom domains included"
echo ""
echo "2. 🌐 **Netlify (Frontend) + Heroku (Backend)**"
echo "   ✅ FREE tier available"
echo "   ✅ Easy setup"
echo "   ✅ Good for learning"
echo ""
echo "3. 🏗️ **DigitalOcean App Platform** - ALL-IN-ONE"
echo "   ✅ Deploy both frontend and backend"
echo "   ✅ $5 credit monthly (FREE for small apps)"
echo "   ✅ Managed database included"
echo ""

echo "🎯 **Quick Start (Vercel + Railway):**"
echo ""
echo "**Step 1: Prepare GitHub Repository**"
echo "1. Create a new repository on GitHub"
echo "2. Push your code:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git remote add origin https://github.com/yourusername/impacthub.git"
echo "   git push -u origin main"
echo ""
echo "**Step 2: Deploy Frontend to Vercel**"
echo "1. Go to https://vercel.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New Project'"
echo "4. Import your repository"
echo "5. Framework: Next.js (auto-detected)"
echo "6. Deploy!"
echo ""
echo "**Step 3: Deploy Backend to Railway**"
echo "1. Go to https://railway.app"
echo "2. Sign up with GitHub"
echo "3. Click 'Deploy from GitHub'"
echo "4. Select your repository"
echo "5. Choose the 'api' folder"
echo "6. Deploy!"
echo ""
echo "**Step 4: Connect Services**"
echo "1. Get your Railway backend URL"
echo "2. In Vercel dashboard, add environment variable:"
echo "   NEXT_PUBLIC_API_URL=https://your-railway-app.railway.app"
echo ""

echo "📱 **Current Local Access:**"
echo "🌐 Frontend: http://localhost:3000"
echo "🔧 Backend: http://localhost:3001"
echo "📱 Network: http://192.168.1.18:3000"
echo ""

echo "📖 **For detailed instructions, see:**"
echo "cat FREE_HOSTING_GUIDE.md"
echo ""

echo "🚀 **Ready to deploy? Choose your preferred option above!**"
