#!/bin/bash

echo "🔧 Fix Vercel Deployment - Environment Variable Issue"
echo "=================================================="
echo ""

echo "❌ **Current Issue:**"
echo "Environment Variable 'NEXT_PUBLIC_API_URL' references Secret 'api_url', which does not exist."
echo ""

echo "✅ **Solution - Two Options:**"
echo ""

echo "🔧 **Option 1: Deploy Backend First (RECOMMENDED)**"
echo ""
echo "1. **Deploy Backend to Railway:**"
echo "   - Go to https://railway.app"
echo "   - Sign up with GitHub"
echo "   - Click 'Deploy from GitHub'"
echo "   - Select your 'muleyvinay/pactaimpact' repository"
echo "   - Choose 'api' folder"
echo "   - Deploy!"
echo ""
echo "2. **Get Railway Backend URL:**"
echo "   - After deployment, copy the Railway URL (e.g., https://pactaimpact-api.railway.app)"
echo ""
echo "3. **Update Vercel Environment Variables:**"
echo "   - Go to your Vercel dashboard"
echo "   - Select your PactaImpact project"
echo "   - Go to Settings → Environment Variables"
echo "   - Add: NEXT_PUBLIC_API_URL = https://your-railway-url.railway.app"
echo "   - Redeploy your frontend"
echo ""

echo "🔧 **Option 2: Use Local Development URL (Temporary)**"
echo ""
echo "1. **Set Environment Variable in Vercel:**"
echo "   - Go to Vercel dashboard → Settings → Environment Variables"
echo "   - Add: NEXT_PUBLIC_API_URL = http://localhost:3001"
echo "   - This is temporary until you deploy the backend"
echo ""
echo "2. **Deploy Backend Later:**"
echo "   - Follow Option 1 steps above"
echo "   - Update the environment variable with the real backend URL"
echo ""

echo "🎯 **Quick Fix Commands:**"
echo ""
echo "# Push the updated vercel.json (removed the problematic env reference)"
echo "git add vercel.json"
echo "git commit -m 'Fix Vercel deployment - remove problematic env reference'"
echo "git push origin main"
echo ""
echo "# This will trigger a new Vercel deployment without the env variable error"
echo ""

echo "📱 **Current Status:**"
echo "✅ Code is on GitHub: https://github.com/muleyvinay/pactaimpact"
echo "✅ Vercel configuration fixed"
echo "⏳ Ready for backend deployment"
echo ""

echo "🚀 **Next Steps:**"
echo "1. Push the updated vercel.json (run commands above)"
echo "2. Deploy backend to Railway"
echo "3. Update Vercel environment variables with Railway URL"
echo "4. Your PactaImpact will be live!"
echo ""

echo "📖 **For detailed instructions, see:**"
echo "cat DEPLOYMENT_QUICK_REFERENCE.md"
echo ""

echo "🔧 **Ready to fix the deployment? Run the commands above!**"
