#!/bin/bash

echo "🔐 GitHub Authentication & Push Guide"
echo "===================================="
echo ""

echo "📋 **Current Status:**"
echo "✅ Repository connected: https://github.com/muleyvinay/pactaimpact"
echo "✅ Code is ready to push"
echo "❌ Authentication needed"
echo ""

echo "🔧 **Option 1: GitHub CLI (Recommended)**"
echo ""
echo "1. Install GitHub CLI:"
echo "   brew install gh"
echo ""
echo "2. Authenticate:"
echo "   gh auth login"
echo "   - Choose GitHub.com"
echo "   - Choose HTTPS"
echo "   - Choose Yes for Git operations"
echo "   - Choose Login with a web browser"
echo ""
echo "3. Push your code:"
echo "   git push -u origin main"
echo ""

echo "🔧 **Option 2: Personal Access Token**"
echo ""
echo "1. Go to https://github.com/settings/tokens"
echo "2. Click 'Generate new token' → 'Generate new token (classic)'"
echo "3. Give it a name: 'PactaImpact Development'"
echo "4. Select scopes: 'repo' (full control)"
echo "5. Click 'Generate token'"
echo "6. Copy the token"
echo ""
echo "7. Use token for authentication:"
echo "   git push https://YOUR_TOKEN@github.com/muleyvinay/pactaimpact.git main"
echo ""

echo "🔧 **Option 3: SSH Key (Most Secure)**"
echo ""
echo "1. Generate SSH key:"
echo "   ssh-keygen -t ed25519 -C 'your-email@example.com'"
echo ""
echo "2. Add to SSH agent:"
echo "   ssh-add ~/.ssh/id_ed25519"
echo ""
echo "3. Copy public key:"
echo "   cat ~/.ssh/id_ed25519.pub"
echo ""
echo "4. Add to GitHub:"
echo "   - Go to https://github.com/settings/keys"
echo "   - Click 'New SSH key'"
echo "   - Paste your public key"
echo ""
echo "5. Change remote to SSH:"
echo "   git remote set-url origin git@github.com:muleyvinay/pactaimpact.git"
echo "   git push -u origin main"
echo ""

echo "🎯 **Quick Start (GitHub CLI):**"
echo ""
echo "Run these commands:"
echo "brew install gh"
echo "gh auth login"
echo "git push -u origin main"
echo ""

echo "📱 **After pushing, deploy to:**"
echo "1. Vercel (Frontend): https://vercel.com"
echo "2. Railway (Backend): https://railway.app"
echo ""

echo "📖 **For detailed deployment guide:**"
echo "cat DEPLOYMENT_QUICK_REFERENCE.md"
echo ""

echo "🚀 **Choose your preferred authentication method above!**"
