#!/bin/bash

echo "🚀 ImpactHub - Push to GitHub"
echo "============================"
echo ""

echo "📋 **Current Status:**"
echo "✅ Code is committed and ready"
echo "✅ All deployment files added"
echo "✅ Repository initialized"
echo ""

echo "🌐 **Step 1: Create GitHub Repository**"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Repository name: impacthub"
echo "3. Description: Web3 Nonprofit Funding Platform"
echo "4. Make it PUBLIC (for free hosting)"
echo "5. Don't initialize with README"
echo "6. Click 'Create repository'"
echo ""

echo "📋 **Step 2: Get Your GitHub Repository URL**"
echo ""
echo "After creating the repository, GitHub will show you a URL like:"
echo "https://github.com/YOUR_USERNAME/impacthub.git"
echo ""
echo "Copy that URL and run the commands below:"
echo ""

echo "🔧 **Step 3: Connect and Push to GitHub**"
echo ""
echo "Replace YOUR_USERNAME with your actual GitHub username:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/impacthub.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

echo "🎯 **Step 4: Deploy to Free Hosting**"
echo ""
echo "After pushing to GitHub, you can deploy to:"
echo ""
echo "1. **Vercel (Frontend)**: https://vercel.com"
echo "   - Connect GitHub account"
echo "   - Import impacthub repository"
echo "   - Root Directory: web"
echo "   - Deploy!"
echo ""
echo "2. **Railway (Backend)**: https://railway.app"
echo "   - Connect GitHub account"
echo "   - Deploy from GitHub"
echo "   - Choose 'api' folder"
echo "   - Deploy!"
echo ""

echo "📱 **Current Local Access:**"
echo "🌐 Frontend: http://localhost:3000"
echo "🔧 Backend: http://localhost:3001"
echo "📱 Network: http://192.168.1.18:3000"
echo ""

echo "🎉 **After deployment, you'll get:**"
echo "✅ Public URL like: https://impacthub.vercel.app"
echo "✅ Custom domain (optional)"
echo "✅ SSL certificate (automatic)"
echo "✅ Global CDN for fast loading"
echo "✅ Automatic deployments on code changes"
echo ""

echo "📖 **For detailed instructions, see:**"
echo "cat DEPLOYMENT_QUICK_REFERENCE.md"
echo ""

echo "🚀 **Ready to push to GitHub? Follow the steps above!**"
