#!/bin/bash

echo "🚀 Setting up GitHub repository for PactaImpact"
echo "============================================="
echo ""

echo "📋 **Step 1: Create GitHub Repository**"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Repository name: pactaimpact"
echo "3. Description: Web3 Nonprofit Funding Platform"
echo "4. Make it PUBLIC (for free hosting)"
echo "5. Don't initialize with README (we already have one)"
echo "6. Click 'Create repository'"
echo ""

echo "📋 **Step 2: Connect Local Repository**"
echo ""
echo "After creating the repository, GitHub will show you commands like:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/pactaimpact.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

echo "📋 **Step 3: Run These Commands**"
echo ""
echo "Replace YOUR_USERNAME with your actual GitHub username:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/pactaimpact.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

echo "🎯 **After pushing to GitHub, you can deploy to:**"
echo ""
echo "1. **Vercel (Frontend)**: https://vercel.com"
echo "   - Connect GitHub account"
echo "   - Import pactaimpact repository"
echo "   - Deploy automatically"
echo ""
echo "2. **Railway (Backend)**: https://railway.app"
echo "   - Connect GitHub account"
echo "   - Deploy from GitHub"
echo "   - Choose 'api' folder"
echo ""

echo "📱 **Current Status:**"
echo "✅ Code is ready for GitHub"
echo "✅ Repository initialized"
echo "✅ All files committed"
echo "✅ Deployment configs created"
echo ""

echo "🚀 **Next Steps:**"
echo "1. Create GitHub repository (follow steps above)"
echo "2. Push code to GitHub"
echo "3. Deploy to Vercel + Railway"
echo "4. Share your live application!"
echo ""

echo "📖 **For detailed instructions, see:**"
echo "cat FREE_HOSTING_GUIDE.md"
echo ""
